# Generated by Django 4.0.6 on 2022-08-22 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_check_customer_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Check',
        ),
        migrations.AddField(
            model_name='customer',
            name='otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
