# Generated by Django 4.0.6 on 2022-08-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.AlterField(
            model_name='customer',
            name='otp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
