# Generated by Django 4.0.6 on 2022-09-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_workers'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
