# Generated by Django 4.0.6 on 2022-09-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('dob', models.CharField(max_length=200, null=True)),
                ('permanent_add', models.CharField(max_length=200, null=True)),
                ('present_add', models.CharField(max_length=200, null=True)),
                ('aadhar', models.CharField(max_length=200, null=True)),
                ('professions', models.CharField(choices=[('Cook', 'Cook'), ('Full-time Maid', 'Full-time Maid'), ('part-time Maid', 'part-time Maid'), ('Gardner', 'Gardner'), ('Driver', 'Driver'), ('Electrician', 'Electrician'), ('Plumber', 'plumber')], max_length=200, null=True)),
                ('Exp', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('aadhar_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('other_photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
