# Generated by Django 4.0.6 on 2022-09-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
    ]
