# Generated by Django 4.0.6 on 2022-09-25 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_application_city_application_pincode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profession',
        ),
    ]
