# Generated by Django 4.0.6 on 2022-09-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='pincode',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
