# Generated by Django 4.0.6 on 2022-09-29 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_workers_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='professions',
            new_name='profession',
        ),
    ]
