# Generated by Django 4.0.6 on 2022-10-06 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0024_employee_exp_employee_aadhar_employee_aadhar_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
