# Generated by Django 4.0.6 on 2022-10-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0027_alter_employee_exp_alter_employee_aadhar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='ser_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
