# Generated by Django 4.0.6 on 2022-10-11 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0028_order_phone_order_ser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.employee'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.customer'),
        ),
    ]
