# Generated by Django 4.0.6 on 2022-10-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0029_order_employee_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Employee',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
    ]
