# Generated by Django 4.0.6 on 2022-10-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0030_rename_employee_order_uid_remove_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ser_name',
        ),
        migrations.AlterField(
            model_name='order',
            name='Domestic',
            field=models.CharField(blank=True, choices=[('Cook', 'Cook'), ('Full-time Maid', 'Full-time Maid'), ('part-time Maid', 'part-time Maid'), ('Gardner', 'Gardner')], max_length=200, null=True),
        ),
    ]
