# Generated by Django 4.0.6 on 2022-10-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0031_remove_order_ser_name_alter_order_domestic'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
