# Generated by Django 4.0.6 on 2022-10-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0032_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'ending'), ('Completed', 'Completed')], max_length=200, null=True),
        ),
    ]
