# Generated by Django 4.0.6 on 2022-10-13 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0035_order_date_created_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.customer'),
        ),
    ]
