# Generated by Django 4.0.6 on 2022-10-14 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0037_alter_order_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='uid',
            new_name='cust_uid',
        ),
        migrations.AddField(
            model_name='order',
            name='cust_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.customer'),
        ),
    ]
