# Generated by Django 4.0.6 on 2022-10-14 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0038_rename_uid_customer_cust_uid_order_cust_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
