# Generated by Django 4.0.6 on 2022-10-19 16:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0040_remove_order_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ord_uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
