# Generated by Django 4.0.6 on 2022-10-24 09:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0046_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ord_uid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
