# Generated by Django 4.0.6 on 2022-10-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0047_alter_order_ord_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ord_uid',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=200),
        ),
    ]
