# Generated by Django 4.0.6 on 2022-10-24 12:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0052_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ord_uid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
