# Generated by Django 4.0.6 on 2022-10-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0053_order_ord_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
