# Generated by Django 4.0.6 on 2022-10-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0055_remove_order_cust_uid_remove_order_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Domestic',
        ),
    ]
