# Generated by Django 4.0.6 on 2022-10-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0056_remove_order_domestic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='custname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='emp_name',
        ),
        migrations.AddField(
            model_name='order',
            name='Domestic',
            field=models.CharField(blank=True, choices=[('Cook', 'Cook'), ('Full-time Maid', 'Full-time Maid'), ('part-time Maid', 'part-time Maid'), ('Gardner', 'Gardner')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cust_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.employee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
