# Generated by Django 4.0.6 on 2022-10-27 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0059_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
