# Generated by Django 4.0.6 on 2022-10-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0060_remove_order_date_created_remove_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='Domestic',
            field=models.CharField(choices=[('Cook', 'Cook'), ('Full-time Maid', 'Full-time Maid'), ('part-time Maid', 'part-time Maid'), ('Gardner', 'Gardner')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
