# Generated by Django 4.0.6 on 2022-10-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0064_remove_order_status_alter_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Domestic',
            field=models.CharField(blank=True, choices=[('Cook', 'Cook'), ('Full-time Maid', 'Full-time Maid'), ('part-time Maid', 'part-time Maid'), ('Gardner', 'Gardner')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=200, null=True),
        ),
    ]
